### ISSUE TITLE
[BUG] Incorrect install path generated if project is configured multiple times in a row

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMaize#104]
**Describe the bug**

CMaize reported it was going to use the wonderful install path:

```
/usr/local/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/py_parallelzone/external/lib/parallelzone/external/lib/parallelzone/external/lib/pkgconfig
```

Thankfully I did not run this in sudo mode, so the directory was never created, but still...

My guess is CMaize is appending to the install path every time configure is called, or this has something to do with how the install paths are manipulated for external projects.

**To Reproduce**
Not 100% sure, but I think it has to do with reconfiguring the project multiple times without blowing away the build directory. I can confirm that blowing away the build directory and retrying the install after a fresh build produces the expected install path.

**Expected behavior**
Things would be installed in a path like `/usr/local/lib/parallelzone/external/lib/pkgconfig`.

**Additional context**
I had also tried having two `cmaize_add_package` commands (the other one was for a `py_parallelzone` target, which is mangled in that path towards the end) only to comment out the second one I added.

**Comment by zachcran** [comment]
I think this is being caused by setting `CMAKE_INSTALL_PREFIX` to the cache during installation [here](https://github.com/CMakePP/CMaize/blob/master/cmake/cmaize/package_managers/cmake/cmake_package_manager.cmake#L281). I don't think it is ever being set back to the original install prefix. I'll get on fixing this soon.

**Comment by zachcran** [comment]
I verified that you can reproduce the issue by reconfiguring the project multiple times. In the short term, you can avoid it if `-DCMAKE_INSTALL_PREFIX=<path>` is used in each `cmake` configure command run.

**Comment by ryanmrichard** [comment]
I think this must have been fixed and/or I can't replicate it by reconfiguring PluginPlay. Feel free to reopen if that's not actually the case.
