### ISSUE TITLE
No make install in master?

### ISSUE THREAD

**Issue by wadejong** [CMakePP/CMaize#45]
(base) wadejong@fryslan:~/NWChemEx-Python/CMakePackagingProject$ !cmake
cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=/home/users/wadejong/NWChemEx-Python/install -DCMAKE_PREFIX_PATH=/home/users/wadejong/NWChemEx-Python/install -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_Fortran_COMPILER=gfortran-8  -DCPP_GITHUB_TOKEN=e90570937183608ee6df7dc1ca6a58da21b18584
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_Fortran_COMPILER
    CPP_GITHUB_TOKEN

-- Build files have been written to: /home/users/wadejong/NWChemEx-Python/CMakePackagingProject/build
(base) wadejong@fryslan:~/NWChemEx-Python/CMakePackagingProject$ cd build
(base) wadejong@fryslan:~/NWChemEx-Python/CMakePackagingProject/build$ make install
make: *** No rule to make target 'install'.  Stop.

**Comment by ryanmrichard** [comment]
There is no install step at the moment. It's on the todo list.

**Comment by ryanmrichard** [comment]
The official TODO for this issue is that projects built with CMaize need to be installable. I have to dive back into the design of CMaize to figure out the best way to do this.
