### ISSUE TITLE
ToolChain Class

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMaize#55]
This class describes the toolchain. In particular it describes options that the user has explicitly set (via the `CMAKE_TOOLCHAIN_FILE`) or that have been added through the class API. 
- Ctor takes a path to a toolchain file
- Needs to be able to compute a hash of itself
- Need ability to add/remove options
- Need ability to deep copy (can't remember if CMakePP has support for this at the moment or not, if not probably want a general copy solution)

**Comment by zachcran** [comment]
@ryanmrichard Was this completed with #71?
