### ISSUE TITLE
Generalize Source / Header Discovery

### ISSUE THREAD

**Issue by wavefunction91** [CMakePP/CMaize#56]
CMaize assumes all C++ source files are `*.cpp` and all headers are `*.hpp`. These should be generalized to include other conventions: `*.cxx`, `.hxx`, `*.hh`, etc. Also, it would be useful to allow for users to manually specify all sources (e.g. in the case of conditional builds)

**Comment by ryanmrichard** [comment]
Just as additional information for this issue, CMake defines the variable `CMAKE_CXX_SOURCE_FILE_EXTENSIONS` which should be used to determine source file extensions. I'm unaware of an analogous include variable (though `CMAKE_CXX_IGNORE_EXTENSIONS` has the standard header extensions in it, but using it would likely confuse the user)

**Comment by wavefunction91** [comment]
Yea, that's definitely more general.

Seeing as though headers don't need to be explicitly handled by the compiler (for 99% of cases mod precompiled headers, which I'm not even sure CMake supports), I can't see a need for an analogous variable for headers. You could create a `CPP_CXX_HEADER_FILE_EXTENSIONS` with some defaults though

**Comment by zachcran** [comment]
I missed directly addressing and potentially closing this issue after this feature was implemented. Generalized source/header discovery in the way you described should be implemented as of PR #84. The rewrite is not live right now, but once we switch over, it will be available.

Things could change between now and when the rewrite goes live, but these points highlight the current implementation. Does this fit what you were thinking?
- Analogous to the `CMAKE_CXX_SOURCE_FILE_EXTENSIONS` variable, which contains default extensions for CXX source files, a `CMAIZE_CXX_INCLUDE_FILE_EXTENSIONS` variable was created to provide default CXX header file extensions. This is useful for us when automatically generating a list of header files.
- These default extensions can be overridden by using keyword arguments passed to `cmaize_add_library()`, `cmaize_add_executable()`, and `cmaize_add_test()` functions.

**Comment by zachcran** [comment]
@ryanmrichard @wavefunction91 Since this is such an old issue, I figured I should put an explicit ping for both of you to make sure you see the update. Thanks!

**Comment by zachcran** [comment]
I'm closing this for now since it seems to be addressed and I have not heard anything to the contrary. Please open it again if something else needs to be done!
